### ISSUE TITLE
Layout Alignment Issue on Website

### ISSUE THREAD

**Issue by Sukhendu2002** [Chris5613/RankRiddler#90]
![Screenshot 2023-05-17 105751](https://github.com/Chris5613/RankRiddler/assets/76804228/fa0005ad-c30e-4b02-a93f-1e27c91980da)

**Comment by Chris5613** [comment]
![72f6181295100b23a8c4a98133d0087e](https://github.com/Chris5613/RankRiddler/assets/24240227/f3ca0fd2-ce6c-43fb-af77-3a0c2b27f865)

The Layout alignment with the 3 photos I fixed just now so that is done. If you want you can try to fix the Navbar because on smaller screens + tablets it doesn't look good at all.
